# Generated by Django 2.2 on 2021-10-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicaldetail',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
